# Site wide configuration

title: "Writing Buddies"
description: "This is a description of my awesome site."
logo: favicon.ico # 120x120 px default image used for Twitter summary card
teaser: book-863418_640.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: https://aspiring-writer.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Aspiring Writer
  email:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline


include:
  - _pages

exclude:
  - _site
  - .jekyll-cache
  - .sass-cache
  - Gemfile
