---
title: Writing Buddies
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
description: A communal blog for writers of all ages and levels to share there work
  for free.
logo: nib-145703_640.png
teaser: paper-3033204_1280.jpg
locale: en
url: http://writing-buddies.siteleaf.net
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title"
kramdown:
  toc_levels: 1..4
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
owner:
  name: Aspiring Writer
  email: aspiring-writer@outlook.com
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: avatar-bravisha.jpg
include:
- _pages
exclude:
- ".jekyll-cache"
- ".sass-cache"
- Gemfile
