---
title: Writing Buddies
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  images:
    title: Images
    output: true
    directory: /images/
description: This is a description of my awesome site.
logo: favicon.ico
teaser: book-863418_640.jpg
locale: en
url: https://aspiring-writer.github.io
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title"
kramdown:
  toc_levels: 1..2..3..4..5
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
owner:
  name: Aspiring Writer
  email: 
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg
include:
- _pages
exclude:
- _site
- ".jekyll-cache"
- ".sass-cache"
- Gemfile
