---
title: Writing Buddies
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A communal blog for writers of all ages and levels to share there work
  for free.
logo: favicon.ico
teaser: book-863418_640.jpg
locale: en
url: https://aspiring-writer.github.io
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title"
kramdown:
  toc_levels: 1..5
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-feed
owner:
  name: Aspiring Writer
  email: aspiring-writer@outlook.com
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: avatar-bravisha.jpg
include:
- _pages
exclude:
- _site
- ".jekyll-cache"
- ".sass-cache"
- Gemfile
