title: Writing Buddies
author: Aspiring-Writer & Friends
avatar: /logo.png
email: yaolson01@gmail.com
description: Plan Together. Write Together. Edit Together. Grow Together.
baseurl: ""
url: "https://aspiring-writer.github.io"

paginate: 5
paginate_path: /page:num/

collections:
  authors:
    output: true

collections_dir: collections

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote-theme: ngzhio/jekyll-theme-hamilton

include: [_pages]

exclude:
  - scripts/
  - README.md
