title: Writing Buddies
author: Aspiring-Writer & Friends
email: yaolson01@gmail.com
description: Plan Together. Write Together. Edit Together. Grow Together.
baseurl: ""
url: "https://aspiring-writer.github.io"

permalink: /:categories/:title

paginate: 10
paginate_path: /page:num/

collections:
  authors:
    output: true
    permalink: /authors/

collections_dir: collections

defaults:
  - scope:
      path: "collections"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

include: [_pages]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
