---
title: Writing Buddies
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: true
  books:
    title: Books
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
- scope:
    path: ''
    type: authors
  values:
    permalink: "/authors/:title"
    layout: author
    avatar: 
    short_bio: 
description: A communal blog for writers of all ages and levels to share there work
  for free.
logo: nib-145703_640.png
teaser-image: paper-3033204_1280.jpg
locale: en
url: http://writing-buddies.siteleaf.net
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title"
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
exclude:
- _site
- ".jekyll-cache"
- ".sass-cache"
- Gemfile
