title: Writing Buddies
author: Aspiring-Writer & Friends
avatar: /logo.png
email: yaolson01@gmail.com
description: Plan Together. Write Together. Edit Together. Grow Together.
baseurl: ""
url: "https://aspiring-writer.github.io"

permalink: /:path

paginate: 5
paginate_path: /page:num/

collections:
  authors:
    output: true

collections_dir: collections

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

include: [_pages]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - scripts/
  - README.md
