baseURL = "https://writing-buddies.netlify.app/"
languageCode = "en-us"
theme = "kitab"
title = "Writing Buddies"

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "Writing Buddies Community"
  description = "Books by the Writing Buddies Community"
  dateFormat = "2006-01-02"
  footer1 = "Write. Read. Share."
  footer2 = "(c) Writing Buddies"