backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: 'stories'
    label: 'Stories'
    folder: 'content/stories'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: "Draft?", name: 'draft', widget: 'boolean', default: 'true', required: false }
      - { label: 'Title', name: 'title', widget: 'string', hint: "Remember: [BOOK] - Chapter..." }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', hint: 'Make sure you spelled it correctly!' }
      - { label: 'Book', name: 'categories', widget: 'list', allow_add: true, label_singular: 'New book' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, label_singular: 'New tag'}
      - { label: "Description", name: 'description', widget: 'text', hint: '(Optional) Default is the first 200 characters of the post', required: false }
      - { label: "Thumbnail", name: 'thumbnail', widget: 'image', allow_multiple: false, choose_url: true, hint: '(Optional) Default is the first image that appears in the post, if any', required: false }
      - { label: "TOC", name: 'toc', widget: 'boolean', default: 'false', required: false }
      